### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_distribution_strategy'

### ISSUE THREAD

**Issue by bhanu-1902** [shag527/Indian-Sign-Language-Recognition#3]
File "C:\Users\USER\anaconda3\lib\site-packages\keras\engine\training.py", line 741, in distribute_strategy
    return self._distribution_strategy or tf.distribute.get_strategy()
AttributeError: 'Sequential' object has no attribute '_distribution_strategy'

I haven't been able to find a workaround for this yet..any comments?

**Comment by shag527** [comment]
I think this is due to change in the tensorflow version! Are you using tensorflow 2??

**Comment by bhanu-1902** [comment]
Yes..tensorflow 2.7

**Comment by bhanu-1902** [comment]
So should I downgrade the files or will I have to use a different way?

**Comment by shag527** [comment]
Can you please try degrading it to tensorflow 1, coz the code is only compatible with tensorflow 1?

**Comment by bhanu-1902** [comment]
> Can you please try degrading it to tensorflow 1, coz the code is only compatible with tensorflow 1?

I downgraded tensorflow to 1.15 and python to 3.7 from 3.9..but now when I click predict sign I get:

ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (C:\Users\USER\anaconda3\lib\site-packages\tensorflow_core\python\eager\context.py)

The solution shows it requires tensorflow upgrade

**Comment by shag527** [comment]
Which keras version are you using??

**Comment by bhanu-1902** [comment]
I was using 2.7..then I shifted to 2.5.0ocr..but no use

**Comment by shag527** [comment]
Can you try installing the versions given in the requirement.txt?

**Comment by bhanu-1902** [comment]
Yep it worked! thanks :).. Also great work btw!
