### ISSUE TITLE
2d array

### ISSUE THREAD

**Issue by snehanals14** [shag527/Indian-Sign-Language-Recognition#6]
Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by shag527** [comment]
Hi @snehanals14,
Can you tell where are you getting this error? And have you installed the same version of libraries given in requirements.txt?

**Comment by snehanals14** [comment]
generate_train_hist.py 
line 121

yes I have installed it

**Comment by shag527** [comment]
Well at line 121, def minibatchkmeans(k, descriptors_list) function (line 59) is called. Can you tell exactly where are you getting thie error? Also, you can check stackoverflow for this. This error basically says:

Any sklearn.Transformer expects a [sample size, n_features] sized array. So there's two scenarios you will have to reshape your data,

If you only have a single sample, you need to reshape it to [1, n_features] sized array
If you have only a single feature, you need to reshape it to [sample size, 1] sized array
